using System.Globalization;
using Masterwork.App.Shared.Services;

namespace Masterwork.App.Shared.Resources;

/// <summary>
/// Hand-written half of the generated <c>AppStrings</c> partial class (see <c>AppStrings.resx</c>,
/// generated by Aigamo.ResXGenerator in <c>GenerateCode</c> mode). That mode picks which baked-in
/// language table <c>AppStrings.SomeKey</c> resolves to by reading <see cref="CultureInfo.CurrentUICulture"/>
/// directly — <see cref="AppSettingsApplier.ApplyCulture"/> is what sets it. <see cref="EffectiveCulture"/>
/// exists for the handful of explicit date/number-formatting call sites elsewhere in the app chrome
/// and guards against <see cref="CultureInfo.CurrentCulture"/> ever being something outside
/// <see cref="AppUiCultures.Supported"/> (e.g. an unrecognized system culture on first launch, before
/// any UI Language has ever been saved) by falling back to <see cref="AppUiCultures.Default"/>.
/// </summary>
partial class AppStrings
{
    public static CultureInfo EffectiveCulture =>
        AppUiCultures.Supported.Any(c => c.Code == CultureInfo.CurrentCulture.Name)
            ? CultureInfo.CurrentCulture
            : CultureInfo.GetCultureInfo(AppUiCultures.Default);
}
